version: '3.8'

services:

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=root
        - RABBITMQ_DEFAULT_PASS=root
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: "redis:alpine"  
    command: redis-server --appendonly yes
    volumes:
        - redis_data:/data

  db:
    image: postgres
    environment:
        - POSTGRES_USER=polls
        - POSTGRES_PASSWORD=hearmeroar
        - POSTGRES_DB=polls_db
    ports:
        - 5433:5432
    volumes:
        - flask_polls_data:/var/lib/postgresql/data  


  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    env_file:
      - env.list 
    links:
      - rabbitmq  
    depends_on:
      - rabbitmq
      - redis

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - env.list
    links:
      - rabbitmq  
    depends_on:
      - rabbitmq    

volumes:
    flask_polls_data:
    redis_data:
